# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class ClientIdFormsBody(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, forms: List[int]=None):  # noqa: E501
        """ClientIdFormsBody - a model defined in Swagger

        :param forms: The forms of this ClientIdFormsBody.  # noqa: E501
        :type forms: List[int]
        """
        self.swagger_types = {
            'forms': List[int]
        }

        self.attribute_map = {
            'forms': 'forms'
        }
        self._forms = forms

    @classmethod
    def from_dict(cls, dikt) -> 'ClientIdFormsBody':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The clientId_forms_body of this ClientIdFormsBody.  # noqa: E501
        :rtype: ClientIdFormsBody
        """
        return util.deserialize_model(dikt, cls)

    @property
    def forms(self) -> List[int]:
        """Gets the forms of this ClientIdFormsBody.


        :return: The forms of this ClientIdFormsBody.
        :rtype: List[int]
        """
        return self._forms

    @forms.setter
    def forms(self, forms: List[int]):
        """Sets the forms of this ClientIdFormsBody.


        :param forms: The forms of this ClientIdFormsBody.
        :type forms: List[int]
        """

        self._forms = forms
